version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile # We will create this Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading in Docker
      - WDS_SOCKET_PORT=0 # CRA specific for HMR behind proxy
    stdin_open: true # For Create React App
    tty: true # For Create React App
  server:
    build: ./server # Assumes Dockerfile exists in ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
